//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace WCFMetaServer
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class Employee
    {
        public Employee()
        {
            this.Employee1 = new HashSet<Employee>();
            this.ProductOrders = new HashSet<ProductOrder>();
            this.Territories = new HashSet<Territory>();
        }
        [DataMember]
        public int EmployeeID { get; set; }
        [DataMember]

        public string LastName { get; set; }
        [DataMember]

        public string FirstName { get; set; }
        [DataMember]

        public string Title { get; set; }
        [DataMember]

        public string TitleOfCourtesy { get; set; }
        [DataMember]

        public Nullable<System.DateTime> BirthDate { get; set; }
        [DataMember]

        public Nullable<System.DateTime> HireDate { get; set; }
        [DataMember]

        public string Address { get; set; }
        [DataMember]

        public string City { get; set; }
        [DataMember]

        public string Region { get; set; }
        [DataMember]

        public string PostalCode { get; set; }
        [DataMember]

        public string Country { get; set; }
        [DataMember]

        public string HomePhone { get; set; }
        public string Extension { get; set; }
        public byte[] Photo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ReportsTo { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public virtual ICollection<Territory> Territories { get; set; }
    }
}
